ALTER TYPE "AssetRole" ADD VALUE IF NOT EXISTS 'PRODUCT_REFERENCE';
ALTER TYPE "AssetRole" ADD VALUE IF NOT EXISTS 'PRODUCT_MOTION_REFERENCE';
ALTER TYPE "AssetRole" ADD VALUE IF NOT EXISTS 'PRODUCT_AUDIO_REFERENCE';
