export const MODEL_CAPABILITIES = {
  "seedance-2": {
    provider: "MUAPI",
    name: "Seedance 2",
    category: "Multi-Asset Character Animation",
    aspectRatios: ["9:16", "16:9", "4:3", "1:1", "3:4"],
    minDuration: 4,
    maxDuration: 15,
    resolutions: ["720p", "1080p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "Yes",
    naturalAvatarInteraction: "Yes",
    apparelWearableSupport: "Yes",
    appScreenDemoSupport: "Partial",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "High multi-asset conditioning (dual image actor + product)",
    maxReferenceImages: 3,
    reliesOnOverlay: false,
    supportedInteractionTypes: ["handheld", "wearable", "accessory", "digital_screen", "furniture_large"],
    supportsImageReference: true,
    supportsVirtualTryOn: true,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "dual_image"
  },
  "fal-bytedance-seedance-v2": {
    provider: "FAL",
    name: "Seedance 2 (Fal.ai)",
    category: "Multi-Asset Character Animation",
    aspectRatios: ["9:16", "16:9", "1:1"],
    minDuration: 4,
    maxDuration: 15,
    resolutions: ["720p", "1080p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "Yes",
    naturalAvatarInteraction: "Yes",
    apparelWearableSupport: "Yes",
    appScreenDemoSupport: "Partial",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "High multi-asset conditioning",
    maxReferenceImages: 3,
    reliesOnOverlay: false,
    supportedInteractionTypes: ["handheld", "wearable", "accessory", "digital_screen", "furniture_large"],
    supportsImageReference: true,
    supportsVirtualTryOn: true,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "dual_image"
  },
  "fal-kling-3-std": {
    provider: "FAL",
    name: "Kling 3.0 Standard (Fal.ai)",
    category: "Visual Motion & Ambient Sound",
    aspectRatios: ["9:16", "16:9", "1:1"],
    minDuration: 5,
    maxDuration: 15,
    resolutions: ["720p", "1080p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "Partial",
    naturalAvatarInteraction: "Yes",
    apparelWearableSupport: "Yes",
    appScreenDemoSupport: "Partial",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "Native Ambient & TTS",
    referenceImageConsistency: "Single reference image conditioning (actor primary)",
    maxReferenceImages: 2,
    reliesOnOverlay: false,
    supportedInteractionTypes: ["handheld", "wearable", "accessory", "digital_screen"],
    supportsImageReference: true,
    supportsVirtualTryOn: true,
    supportsGenerateAudio: true,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "grok-video": {
    provider: "MUAPI",
    name: "Grok Video",
    category: "Visual Motion Video",
    aspectRatios: ["9:16", "16:9", "2:3", "3:2", "1:1"],
    minDuration: 3,
    maxDuration: 15,
    resolutions: ["480p", "720p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "Partial",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Single reference image; product details driven by text prompt",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "digital_screen", "furniture_large"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "veo-3-1": {
    provider: "MUAPI",
    name: "Veo 3.1",
    category: "High-Fidelity Visual Motion",
    aspectRatios: ["9:16", "16:9"],
    minDuration: 8,
    maxDuration: 15,
    resolutions: ["720p", "1080p", "4k"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "Partial",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Single reference image; high prompt fidelity",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "furniture_large"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "happy-horse": {
    provider: "MUAPI",
    name: "Happy Horse 1",
    category: "Visual Animation",
    aspectRatios: ["9:16", "16:9", "1:1", "4:3", "3:4"],
    minDuration: 3,
    maxDuration: 15,
    resolutions: ["720p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "No",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "No",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Basic single image conditioning",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "fal-luma-ray-v2": {
    provider: "FAL",
    name: "Luma Ray 2 (Fal.ai)",
    category: "Visual Motion Video",
    aspectRatios: ["9:16", "16:9"],
    minDuration: 5,
    maxDuration: 15,
    resolutions: ["720p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "Partial",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Single reference image conditioning",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "digital_screen"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  // ── Kling Family ──────────────────────────────────────────────────────────
  "kling-3-std": {
    provider: "FAL",
    name: "Kling 3.0 Standard",
    category: "Visual Motion & Ambient Sound",
    aspectRatios: ["9:16", "16:9", "1:1"],
    minDuration: 5,
    maxDuration: 15,
    resolutions: ["720p", "1080p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "Partial",
    naturalAvatarInteraction: "Yes",
    apparelWearableSupport: "Yes",
    appScreenDemoSupport: "Partial",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "Native Ambient & TTS",
    referenceImageConsistency: "Single reference image conditioning",
    maxReferenceImages: 2,
    reliesOnOverlay: false,
    supportedInteractionTypes: ["handheld", "wearable", "accessory", "digital_screen"],
    supportsImageReference: true,
    supportsVirtualTryOn: true,
    supportsGenerateAudio: true,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "kling-3-pro": {
    provider: "FAL",
    name: "Kling 3.0 Pro",
    category: "Visual Motion & Ambient Sound",
    aspectRatios: ["9:16", "16:9", "1:1"],
    minDuration: 5,
    maxDuration: 15,
    resolutions: ["720p", "1080p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "Partial",
    naturalAvatarInteraction: "Yes",
    apparelWearableSupport: "Yes",
    appScreenDemoSupport: "Partial",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "Native Ambient & TTS",
    referenceImageConsistency: "High-fidelity single reference image",
    maxReferenceImages: 2,
    reliesOnOverlay: false,
    supportedInteractionTypes: ["handheld", "wearable", "accessory", "digital_screen"],
    supportsImageReference: true,
    supportsVirtualTryOn: true,
    supportsGenerateAudio: true,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "kling-1.5-std": {
    provider: "FAL",
    name: "Kling 1.5 Standard",
    category: "Visual Motion Video",
    aspectRatios: ["9:16", "16:9", "1:1"],
    minDuration: 5,
    maxDuration: 10,
    resolutions: ["720p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "Partial",
    naturalAvatarInteraction: "Partial",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Single reference image",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "digital_screen"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "kling-1.5-pro": {
    provider: "FAL",
    name: "Kling 1.5 Pro",
    category: "Visual Motion Video",
    aspectRatios: ["9:16", "16:9", "1:1"],
    minDuration: 5,
    maxDuration: 10,
    resolutions: ["720p", "1080p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "Partial",
    naturalAvatarInteraction: "Partial",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "High-fidelity single reference image",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "digital_screen"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "kling-avatar-v2": {
    provider: "FAL",
    name: "Kling Avatar V2",
    category: "Avatar / Talking Head",
    aspectRatios: ["9:16", "16:9", "1:1"],
    minDuration: 5,
    maxDuration: 15,
    resolutions: ["720p", "1080p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "Yes",
    naturalAvatarInteraction: "Yes",
    apparelWearableSupport: "Yes",
    appScreenDemoSupport: "Partial",
    accurateLipSyncSupport: "Native",
    voiceoverSupport: "Native TTS via audio_url",
    referenceImageConsistency: "Avatar face locked from image_url",
    maxReferenceImages: 1,
    reliesOnOverlay: false,
    supportedInteractionTypes: ["handheld", "wearable", "accessory", "digital_screen"],
    supportsImageReference: true,
    supportsVirtualTryOn: true,
    supportsGenerateAudio: true,
    supportsNativeLipSync: true,
    productReferenceMode: "prompt_only"
  },
  // ── Minimax ───────────────────────────────────────────────────────────────
  "minimax-video-01-live": {
    provider: "FAL",
    name: "Minimax Hailuo Video Live",
    category: "Visual Motion Video",
    aspectRatios: ["9:16", "16:9", "1:1"],
    minDuration: 5,
    maxDuration: 15,
    resolutions: ["720p", "1080p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "Partial",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Single reference image",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "digital_screen", "furniture_large"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "minimax-video-01": {
    provider: "FAL",
    name: "Minimax Standard",
    category: "Visual Motion Video",
    aspectRatios: ["9:16", "16:9", "1:1"],
    minDuration: 5,
    maxDuration: 15,
    resolutions: ["720p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "Partial",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Single reference image",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "digital_screen", "furniture_large"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  // ── Luma ─────────────────────────────────────────────────────────────────
  "luma-ray-2": {
    provider: "FAL",
    name: "Luma Ray 2",
    category: "Visual Motion Video",
    aspectRatios: ["9:16", "16:9"],
    minDuration: 5,
    maxDuration: 15,
    resolutions: ["720p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "Partial",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Single reference image conditioning",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "digital_screen"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  // ── Wan ───────────────────────────────────────────────────────────────────
  "wan-video": {
    provider: "FAL",
    name: "Wan Video",
    category: "Visual Motion Video",
    aspectRatios: ["9:16", "16:9", "1:1"],
    minDuration: 5,
    maxDuration: 15,
    resolutions: ["720p", "1080p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "Partial",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Single reference image",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "digital_screen", "furniture_large"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  // ── Seedance ─────────────────────────────────────────────────────────────
  "seedance-lite": {
    provider: "FAL",
    name: "Seedance Lite",
    category: "Multi-Asset Character Animation",
    aspectRatios: ["9:16", "16:9", "1:1"],
    minDuration: 4,
    maxDuration: 10,
    resolutions: ["720p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "Yes",
    naturalAvatarInteraction: "Yes",
    apparelWearableSupport: "Yes",
    appScreenDemoSupport: "Partial",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Dual reference image (actor + product)",
    maxReferenceImages: 2,
    reliesOnOverlay: false,
    supportedInteractionTypes: ["handheld", "wearable", "accessory", "digital_screen"],
    supportsImageReference: true,
    supportsVirtualTryOn: true,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "dual_image"
  },
  "seedance-pro": {
    provider: "FAL",
    name: "Seedance Pro",
    category: "Multi-Asset Character Animation",
    aspectRatios: ["9:16", "16:9", "1:1"],
    minDuration: 4,
    maxDuration: 15,
    resolutions: ["720p", "1080p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "Yes",
    naturalAvatarInteraction: "Yes",
    apparelWearableSupport: "Yes",
    appScreenDemoSupport: "Partial",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Dual reference image (actor + product), high fidelity",
    maxReferenceImages: 3,
    reliesOnOverlay: false,
    supportedInteractionTypes: ["handheld", "wearable", "accessory", "digital_screen", "furniture_large"],
    supportsImageReference: true,
    supportsVirtualTryOn: true,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "dual_image"
  },
  // ── Other Fal.ai Models ──────────────────────────────────────────────────
  "hunyuan-video": {
    provider: "FAL",
    name: "HunyuanVideo",
    category: "Visual Motion Video",
    aspectRatios: ["16:9", "9:16"],
    minDuration: 5,
    maxDuration: 15,
    resolutions: ["720p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "Partial",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Single reference image",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "digital_screen"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "cogvideox-5b": {
    provider: "FAL",
    name: "CogVideoX-5B",
    category: "Visual Motion Video",
    aspectRatios: ["16:9"],
    minDuration: 5,
    maxDuration: 10,
    resolutions: ["720p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "No",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Single reference image",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "furniture_large"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "mochi-v1": {
    provider: "FAL",
    name: "Mochi v1",
    category: "Visual Motion Video",
    aspectRatios: ["16:9"],
    minDuration: 5,
    maxDuration: 10,
    resolutions: ["720p"],
    nativeI2V: "No",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "No",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Text-to-video only",
    maxReferenceImages: 0,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "furniture_large"],
    supportsImageReference: false,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "ltx-video": {
    provider: "FAL",
    name: "LTX Video",
    category: "Visual Motion Video",
    aspectRatios: ["16:9", "9:16"],
    minDuration: 5,
    maxDuration: 15,
    resolutions: ["720p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "No",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Single reference image",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "furniture_large"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "vidu-q1": {
    provider: "FAL",
    name: "Vidu Q1",
    category: "Visual Motion Video",
    aspectRatios: ["16:9", "9:16", "1:1"],
    minDuration: 5,
    maxDuration: 15,
    resolutions: ["720p", "1080p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "Partial",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Single reference image",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "digital_screen"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "haiper-video-v2.5": {
    provider: "FAL",
    name: "Haiper Video 2.5",
    category: "Visual Motion Video",
    aspectRatios: ["16:9", "9:16"],
    minDuration: 5,
    maxDuration: 15,
    resolutions: ["720p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "Partial",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Single reference image",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "digital_screen"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "gencore-video": {
    provider: "FAL",
    name: "Gencore Video",
    category: "Visual Motion Video",
    aspectRatios: ["16:9", "9:16", "1:1"],
    minDuration: 5,
    maxDuration: 15,
    resolutions: ["720p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "Partial",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "Relies on Overlay",
    accurateLipSyncSupport: "External",
    voiceoverSupport: "TTS",
    referenceImageConsistency: "Single reference image",
    maxReferenceImages: 1,
    reliesOnOverlay: true,
    supportedInteractionTypes: ["handheld", "accessory", "digital_screen", "furniture_large"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: false,
    supportsNativeLipSync: false,
    productReferenceMode: "prompt_only"
  },
  "sadtalker": {
    provider: "FAL",
    name: "SadTalker",
    category: "Avatar / Talking Head",
    aspectRatios: ["1:1"],
    minDuration: 5,
    maxDuration: 30,
    resolutions: ["720p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "Yes",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "No",
    accurateLipSyncSupport: "Native",
    voiceoverSupport: "Native audio_url",
    referenceImageConsistency: "Face locked from source image",
    maxReferenceImages: 1,
    reliesOnOverlay: false,
    supportedInteractionTypes: ["handheld"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: true,
    supportsNativeLipSync: true,
    productReferenceMode: "prompt_only"
  },
  "musetalk": {
    provider: "FAL",
    name: "MuseTalk",
    category: "Avatar / Talking Head",
    aspectRatios: ["1:1"],
    minDuration: 5,
    maxDuration: 30,
    resolutions: ["720p"],
    nativeI2V: "Yes",
    nativeProductIntegration: "No",
    naturalAvatarInteraction: "Yes",
    apparelWearableSupport: "No",
    appScreenDemoSupport: "No",
    accurateLipSyncSupport: "Native",
    voiceoverSupport: "Native audio_url",
    referenceImageConsistency: "Face locked from source image",
    maxReferenceImages: 1,
    reliesOnOverlay: false,
    supportedInteractionTypes: ["handheld"],
    supportsImageReference: true,
    supportsVirtualTryOn: false,
    supportsGenerateAudio: true,
    supportsNativeLipSync: true,
    productReferenceMode: "prompt_only"
  }
};

/**
 * Validates model capability for specific workflow type and native integration demands.
 * Prevents routing native-integration requests to unsupported or overlay-only models.
 */
export function validateModelForWorkflow({ modelId, workflowType = "PRODUCT_AD", productType = "handheld", requireNativeIntegration = false }) {
  const cap = MODEL_CAPABILITIES[modelId];

  if (!cap) {
    return {
      valid: false,
      code: "INVALID_MODEL",
      error: `Model ID '${modelId}' is not recognized in the platform capability matrix.`,
      recommendedModels: ["seedance-2", "fal-bytedance-seedance-v2"]
    };
  }

  // Native integration requirement check: Do NOT route native-integration requests to unsupported models
  if (requireNativeIntegration && cap.reliesOnOverlay) {
    const recommended = Object.keys(MODEL_CAPABILITIES).filter(id => !MODEL_CAPABILITIES[id].reliesOnOverlay);
    return {
      valid: false,
      code: "MODEL_NATIVE_INTEGRATION_UNSUPPORTED",
      error: `Model '${cap.name}' cannot fulfill native scene integration requests and relies on 2D overlays. Please select a model supporting native image conditioning (e.g. Seedance 2 or Kling 3.0).`,
      recommendedModels: recommended
    };
  }

  if (workflowType === "PRODUCT_AD" && productType === "wearable" && !cap.supportsVirtualTryOn) {
    return {
      valid: false,
      code: "UNSUPPORTED_CAPABILITY",
      error: `Selected model '${cap.name}' does not support apparel / wearable product integration. Please select Seedance 2 or Kling 3.0 Standard.`,
      recommendedModels: ["seedance-2", "fal-bytedance-seedance-v2", "fal-kling-3-std"]
    };
  }

  return { valid: true, capability: cap };
}

/**
 * Validates request parameters and product interaction types against verified model capability matrix
 */
export function validateModelCapability(modelId, settings = {}, productType = "handheld") {
  const cap = MODEL_CAPABILITIES[modelId];

  if (!cap) {
    return {
      valid: false,
      code: "INVALID_MODEL",
      error: `Model ID '${modelId}' is not recognized in the provider capability matrix.`
    };
  }

  // 1. Resolve & Validate Aspect Ratio ("Auto" resolves to "9:16" or primary supported ratio)
  let aspect = settings.aspect_ratio || settings.aspectRatio || "9:16";
  if (String(aspect).toLowerCase() === "auto" || !cap.aspectRatios.includes(aspect)) {
    aspect = cap.aspectRatios.includes("9:16") ? "9:16" : cap.aspectRatios[0];
  }

  // 2. Resolve & Validate Duration
  let duration = settings.duration;
  if (String(duration).toLowerCase() === "auto" || !duration) {
    duration = 5;
  } else {
    duration = typeof duration === "number" ? duration : (parseInt(duration) || 5);
  }
  if (duration < cap.minDuration) duration = cap.minDuration;
  if (duration > cap.maxDuration) duration = cap.maxDuration;

  // 3. Resolve & Validate Resolution
  let resolution = settings.resolution || "720p";
  if (String(resolution).toLowerCase() === "auto" || !cap.resolutions.includes(resolution)) {
    resolution = cap.resolutions.includes("720p") ? "720p" : cap.resolutions[0];
  }

  // Product Interaction Capability Check
  if (productType === "wearable" && !cap.supportsVirtualTryOn) {
    return {
      valid: false,
      code: "UNSUPPORTED_CAPABILITY",
      error: `Selected model '${cap.name}' does not support virtual try-on / wearable apparel integration. Please select Seedance 2 or Kling 3.0.`
    };
  }

  if (!cap.supportedInteractionTypes.includes(productType)) {
    return {
      valid: false,
      code: "UNSUPPORTED_CAPABILITY",
      error: `Model '${cap.name}' cannot handle '${productType}' interaction. Supported interaction types: ${cap.supportedInteractionTypes.join(", ")}.`
    };
  }

  return {
    valid: true,
    capability: cap,
    resolvedSettings: {
      aspect_ratio: aspect,
      duration,
      resolution
    }
  };
}

