export const PRESETS_LIBRARY = [
  {
    id: "preset-01",
    code: "01",
    name: "Mobile App — Screen-to-Life Demo",
    category: "Apps & SaaS",
    tag: "Mobile App",
    bestFor: "Consumer apps, productivity apps, finance tools, marketplaces, learning apps",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Authentic iPhone UGC of [Avatar] presenting [Brand]. Quick selfie framing opening into macro taps on the app screens. Demonstrates [Primary Benefit] and finishes with a clear [CTA]."
  },
  {
    id: "preset-02",
    code: "02",
    name: "SaaS — Founder-Led Dashboard Walkthrough",
    category: "Apps & SaaS",
    tag: "B2B SaaS",
    bestFor: "B2B SaaS, analytics, CRM, AI tools, workflow software",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Founder-style UGC at a modern desk. [Avatar] speaks directly to camera beside a laptop displaying [Brand] dashboard, showcasing core feature workflow and key metric payoff."
  },
  {
    id: "preset-03",
    code: "03",
    name: "Physical Product — Problem/Solution Transformation",
    category: "Product & E-Com",
    tag: "Transformation",
    bestFor: "Household products, tools, organizers, accessories, convenience products",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Raw iPhone UGC. [Avatar] identifies [Pain Point], demonstrates [Target Product] in action, and reveals the [Primary Benefit] transformation result."
  },
  {
    id: "preset-04",
    code: "04",
    name: "Unboxing — Genuine First Impression",
    category: "Product & E-Com",
    tag: "Unboxing",
    bestFor: "E-commerce launches, subscription boxes, gadgets, beauty, gifts",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Phone-camera unboxing. Top-down view as [Avatar] lifts [Target Product] from packaging, showcasing textures, details, and authentic first-impression reaction."
  },
  {
    id: "preset-05",
    code: "05",
    name: "How-To — Three-Step Tutorial",
    category: "Tutorials & How-To",
    tag: "Tutorial",
    bestFor: "Products requiring education, setup, assembly, skincare application, tools",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Clear instructional 3-step UGC tutorial. [Avatar] guides through step 1, step 2, and step 3 of using [Target Product], ending on the finished result."
  },
  {
    id: "preset-06",
    code: "06",
    name: "Comparison — Ordinary Option vs Product",
    category: "Showcase & Ads",
    tag: "Comparison",
    bestFor: "Differentiated products with demonstrable advantages",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Side-by-side UGC comparison test. [Avatar] compares generic alternative vs [Target Product], demonstrating key performance advantages and [Primary Benefit]."
  },
  {
    id: "preset-07",
    code: "07",
    name: "Listicle — Three Reasons I Keep Using It",
    category: "Showcase & Ads",
    tag: "Listicle",
    bestFor: "Broad-benefit products, retargeting, feature education",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Energetic talking-head UGC. [Avatar] holds [Target Product] and rapidly covers 3 core reasons why they use it daily, highlighting features in action."
  },
  {
    id: "preset-08",
    code: "08",
    name: "Personal Story — 'I Didn't Expect This'",
    category: "Lifestyle & Story",
    tag: "Testimonial",
    bestFor: "Testimonial-style ads, discovery stories, lifestyle products",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Intimate personal story UGC. [Avatar] speaks candidly to camera about their unexpected positive experience after integrating [Target Product] into their routine."
  },
  {
    id: "preset-09",
    code: "09",
    name: "Daily Routine — Product Naturally Embedded",
    category: "Lifestyle & Story",
    tag: "Daily Routine",
    bestFor: "Habit products, accessories, wellness tools, home and personal-care items",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Day-in-the-life UGC clip. [Avatar] goes through their morning routine, naturally reaching for and using [Target Product] to reduce daily friction."
  },
  {
    id: "preset-10",
    code: "10",
    name: "Travel Packing — What Fits Inside",
    category: "Product & E-Com",
    tag: "Travel & Packing",
    bestFor: "Bags, organizers, luggage, outdoor equipment",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Top-down packing POV UGC. [Avatar] packs essential travel items into [Target Product], proving storage capacity, pocket organization, and portability."
  },
  {
    id: "preset-11",
    code: "11",
    name: "Desk Setup — Gadget Productivity Upgrade",
    category: "Product & E-Com",
    tag: "Desk Setup",
    bestFor: "Electronics, desk accessories, chargers, keyboards, creator tools",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Crisp desk setup B-roll with talking-head hook. [Avatar] mounts and connects [Target Product] to solve clutter and boost workplace productivity."
  },
  {
    id: "preset-12",
    code: "12",
    name: "Kitchen — Recipe or Food-Prep Integration",
    category: "Lifestyle & Story",
    tag: "Kitchen & Food",
    bestFor: "Kitchen tools, appliances, food storage, cookware, ingredients",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Bright home-kitchen UGC. Overhead prep and macro texture shots of [Avatar] using [Target Product] for quick, clean food preparation."
  },
  {
    id: "preset-13",
    code: "13",
    name: "Home Organization — Satisfying Reset",
    category: "Lifestyle & Story",
    tag: "Organization",
    bestFor: "Storage, cleaning accessories, organizers, space-saving products",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Satisfying before & after reset UGC. [Avatar] sorts items into [Target Product], revealing a perfectly organized drawer/shelf layout."
  },
  {
    id: "preset-14",
    code: "14",
    name: "Cleaning Product — Real-Time Demonstration",
    category: "Tutorials & How-To",
    tag: "Cleaning Demo",
    bestFor: "Brushes, cloths, small cleaning tools, surface-care products",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Direct iPhone cleaning pass. Macro surface detail of [Avatar] applying [Target Product] to clean stubborn mess in one smooth motion."
  },
  {
    id: "preset-15",
    code: "15",
    name: "Parent Perspective — Calm Bedtime or Care Routine",
    category: "Lifestyle & Story",
    tag: "Family & Care",
    bestFor: "Baby-safe comfort products, nursery products, family organizers, sound machines",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Gentle nursery UGC from caregiver perspective. [Avatar] activates [Target Product] during evening care routine, creating a soothing home environment."
  },
  {
    id: "preset-16",
    code: "16",
    name: "Pet Product — Owner-and-Pet Demonstration",
    category: "Lifestyle & Story",
    tag: "Pet Care",
    bestFor: "Pet toys, grooming tools, feeders, travel accessories",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Playful pet-eye-level UGC. [Avatar] introduces [Target Product] to their pet, demonstrating natural pet interaction and easy cleanup."
  },
  {
    id: "preset-17",
    code: "17",
    name: "Fashion Product — Fit, Detail, and Styling",
    category: "Fashion & Beauty",
    tag: "Fashion Styling",
    bestFor: "Adult clothing, shoes, bags, watches, jewelry, accessories",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Natural fashion UGC mirror shot. [Avatar] showcases fit, fabric texture, hardware details, and styling movement wearing [Target Product]."
  },
  {
    id: "preset-18",
    code: "18",
    name: "Beauty Product — Texture and Routine Demo",
    category: "Fashion & Beauty",
    tag: "Beauty Routine",
    bestFor: "Cosmetics and non-medical skincare used by adults",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Close vanity UGC demo. Macro swatch and application of [Target Product] on skin, highlighting real texture, glow, and natural finish."
  },
  {
    id: "preset-19",
    code: "19",
    name: "ASMR — Tactile Product Close-Up",
    category: "Showcase & Ads",
    tag: "ASMR Tactile",
    bestFor: "Packaging, stationery, accessories, textured goods, satisfying mechanisms",
    defaultDuration: 12,
    defaultAspect: "9:16",
    prompt: "Tactile ASMR close-up. Slow deliberate hands opening, clicking, and operating [Target Product] with crisp auditory focus."
  },
  {
    id: "preset-20",
    code: "20",
    name: "Luxury Product — Understated Editorial UGC",
    category: "Fashion & Beauty",
    tag: "Luxury Editorial",
    bestFor: "Premium accessories, fragrance packaging, leather goods, design objects",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Understated luxury UGC with directional window lighting. Push-in macro focus on material craftsmanship and elegant usage of [Target Product]."
  },
  {
    id: "preset-21",
    code: "21",
    name: "Outdoor Adventure — Built for the Elements",
    category: "Lifestyle & Story",
    tag: "Outdoor Gear",
    bestFor: "Bags, outerwear, bottles, portable gear, outdoor accessories",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Outdoor adventure UGC footage. [Avatar] packs [Target Product] at trailhead and demonstrates durability and weather resistance in nature."
  },
  {
    id: "preset-22",
    code: "22",
    name: "Car Talk — Candid Recommendation",
    category: "Showcase & Ads",
    tag: "Car Talk",
    bestFor: "Services, apps, subscriptions, compact products, story-based ads",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Candid front-facing phone footage mounted inside a parked car. [Avatar] speaks naturally to camera, recommending [Brand] as a essential life hack."
  },
  {
    id: "preset-23",
    code: "23",
    name: "Street Interview — One-Question Social Proof",
    category: "Showcase & Ads",
    tag: "Social Proof",
    bestFor: "Brand awareness, simple value propositions, event or location campaigns",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Handheld street interview UGC. Quick-cut responses from avatars answering key question about [Target Product], driving strong social proof."
  },
  {
    id: "preset-24",
    code: "24",
    name: "Podcast Clip — Conversational Authority",
    category: "Apps & SaaS",
    tag: "Podcast Clip",
    bestFor: "SaaS, education, services, considered purchases, founder messaging",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Vertical podcast studio clip. [Avatar] speaks into desktop microphone explaining a key industry problem solved by [Brand]."
  },
  {
    id: "preset-25",
    code: "25",
    name: "Green-Screen Commentary — React and Explain",
    category: "Apps & SaaS",
    tag: "Green-Screen",
    bestFor: "Apps, websites, product pages, feature announcements, educational ads",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Social green-screen commentary format. [Avatar] in foreground points toward background app/website screen, breaking down [Primary Benefit]."
  },
  {
    id: "preset-26",
    code: "26",
    name: "Screen Recording + Facecam — Live Use Case",
    category: "Apps & SaaS",
    tag: "Screen Recording",
    bestFor: "Apps, websites, browser extensions, SaaS, online services",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Screen-recording with avatar facecam overlay. Demonstrates live cursor taps navigating [Brand] UI to complete a key workflow."
  },
  {
    id: "preset-27",
    code: "27",
    name: "Myth vs Fact — Fast Educational Correction",
    category: "Tutorials & How-To",
    tag: "Myth vs Fact",
    bestFor: "Product education, objection handling, misunderstood categories",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Fast Myth vs Fact UGC format. [Avatar] debunks common misconception about product category, proving the truth with [Target Product]."
  },
  {
    id: "preset-28",
    code: "28",
    name: "FAQ — Rapid Objection Answers",
    category: "Showcase & Ads",
    tag: "Rapid FAQ",
    bestFor: "Retargeting, high-consideration products, pricing or setup objections",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Rapid FAQ UGC response. [Avatar] holds [Target Product] and answers top 3 customer questions directly with visual proof."
  },
  {
    id: "preset-29",
    code: "29",
    name: "Offer Announcement — Clear, Honest Promotion",
    category: "Showcase & Ads",
    tag: "Offer Promo",
    bestFor: "Sales, bundles, launches, free trials, seasonal campaigns",
    defaultDuration: 12,
    defaultAspect: "9:16",
    prompt: "Direct offer promo UGC. [Avatar] presents [Target Product] bundle offer, highlighting price value, bonus items, and CTA."
  },
  {
    id: "preset-30",
    code: "30",
    name: "Stop-Motion Tabletop — Product Feature Sequence",
    category: "Product & E-Com",
    tag: "Stop-Motion",
    bestFor: "Small products, kits, stationery, accessories, packaging, bundles",
    defaultDuration: 12,
    defaultAspect: "9:16",
    prompt: "Overhead stop-motion tabletop animation. Included components assemble geometrically around [Target Product] in satisfying sequence."
  },
  {
    id: "preset-31",
    code: "31",
    name: "Split-Screen — Reaction + Demonstration",
    category: "Showcase & Ads",
    tag: "Split-Screen",
    bestFor: "Satisfying products, app outcomes, tools, compact explainers",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Vertical split-screen format. Top panel shows [Avatar] reacting, bottom panel shows simultaneous product demonstration."
  },
  {
    id: "preset-32",
    code: "32",
    name: "Founder Story — Why We Built This",
    category: "Apps & SaaS",
    tag: "Founder Story",
    bestFor: "New brands, SaaS, mission-led products, crowdfunding-style launches",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Honest founder story UGC. [Avatar] shares the origin story behind creating [Brand] to solve a personal frustration."
  },
  {
    id: "preset-33",
    code: "33",
    name: "Local Service — From Problem to Booked",
    category: "Services",
    tag: "Local Service",
    bestFor: "Cleaning, repair, tutoring, design, professional and home services",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Local service UGC story. [Avatar] demonstrates booking local service on phone, followed by fast professional work and clean result."
  },
  {
    id: "preset-34",
    code: "34",
    name: "Gift Reaction — Thoughtful Reveal",
    category: "Lifestyle & Story",
    tag: "Gift Reveal",
    bestFor: "Gifts, personalized items, keepsakes, seasonal products",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Warm gift handoff UGC. [Avatar] unwraps [Target Product], displaying genuine joy and admiring custom details."
  },
  {
    id: "preset-35",
    code: "35",
    name: "Image-Led Showcase — Animate Product Photography",
    category: "Product & E-Com",
    tag: "Image Showcase",
    bestFor: "Sellers with strong product images but limited video footage",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Animated product photography showcase. Gentle depth parallax and macro push-in shots animating still images of [Target Product]."
  },
  {
    id: "preset-36",
    code: "36",
    name: "Reference-Led Recreation — Match Creative Grammar",
    category: "Showcase & Ads",
    tag: "Creative Grammar",
    bestFor: "Users supplying a reference ad whose pacing, framing, or structure they want to emulate",
    defaultDuration: 15,
    defaultAspect: "9:16",
    prompt: "Recreates pacing, framing, and structure of reference ad for [Target Product] with custom [Avatar] and brand script."
  }
];
