-- Preserve canonical generation input semantics through CreationAsset persistence.
ALTER TYPE "AssetRole" ADD VALUE IF NOT EXISTS 'SOURCE_IMAGE';
ALTER TYPE "AssetRole" ADD VALUE IF NOT EXISTS 'SOURCE_VIDEO';
ALTER TYPE "AssetRole" ADD VALUE IF NOT EXISTS 'REFERENCE_IMAGE';
ALTER TYPE "AssetRole" ADD VALUE IF NOT EXISTS 'REFERENCE_VIDEO';
ALTER TYPE "AssetRole" ADD VALUE IF NOT EXISTS 'REFERENCE_AUDIO';
ALTER TYPE "AssetRole" ADD VALUE IF NOT EXISTS 'START_FRAME';
ALTER TYPE "AssetRole" ADD VALUE IF NOT EXISTS 'END_FRAME';
