export const PRICING_REVISION = Object.freeze({ id: "2026-08-auth-v1", customerListValuePerCreditMicroUsd: 41_500n, netRevenuePerCreditFloorMicroUsd: 30_000n, targetContributionMarginBps: 3000, maxFullyLoadedCostPerCreditMicroUsd: 21_000n, polarTransactionFeeBps: 500, polarFixedFeeMicroUsd: 500_000n });
export const PLAN_CODES = Object.freeze({ EXPLORER: "EXPLORER", STARTER_MONTHLY: "STARTER_MONTHLY", STARTER_ANNUAL: "STARTER_ANNUAL", GROWTH_MONTHLY: "GROWTH_MONTHLY", GROWTH_ANNUAL: "GROWTH_ANNUAL", AGENCY_MONTHLY: "AGENCY_MONTHLY", AGENCY_ANNUAL: "AGENCY_ANNUAL" });
export const PLANS = Object.freeze({
  EXPLORER: { code: PLAN_CODES.EXPLORER, priceMicroUsd: 2_990_000n, credits: 50, interval: "ONE_TIME", seats: 1, workspaces: 1 },
  STARTER_MONTHLY: { code: PLAN_CODES.STARTER_MONTHLY, priceMicroUsd: 29_000_000n, credits: 700, interval: "MONTHLY", seats: 1, workspaces: 1 }, STARTER_ANNUAL: { code: PLAN_CODES.STARTER_ANNUAL, priceMicroUsd: 278_400_000n, credits: 700, interval: "ANNUAL", seats: 1, workspaces: 1 },
  GROWTH_MONTHLY: { code: PLAN_CODES.GROWTH_MONTHLY, priceMicroUsd: 79_000_000n, credits: 1900, interval: "MONTHLY", seats: 3, workspaces: 3 }, GROWTH_ANNUAL: { code: PLAN_CODES.GROWTH_ANNUAL, priceMicroUsd: 758_400_000n, credits: 1900, interval: "ANNUAL", seats: 3, workspaces: 3 },
  AGENCY_MONTHLY: { code: PLAN_CODES.AGENCY_MONTHLY, priceMicroUsd: 179_000_000n, credits: 4300, interval: "MONTHLY", seats: 10, workspaces: 10 }, AGENCY_ANNUAL: { code: PLAN_CODES.AGENCY_ANNUAL, priceMicroUsd: 1_718_400_000n, credits: 4300, interval: "ANNUAL", seats: 10, workspaces: 10 }
});
export function calculateRequiredCredits(costs) { const fullyLoadedCost = Object.values(costs).reduce((sum, value) => sum + BigInt(value || 0), 0n); const rawCredits = (fullyLoadedCost + PRICING_REVISION.maxFullyLoadedCostPerCreditMicroUsd - 1n) / PRICING_REVISION.maxFullyLoadedCostPerCreditMicroUsd; const quotedCredits = ((rawCredits + 4n) / 5n) * 5n; return { fullyLoadedCostMicroUsd: fullyLoadedCost, rawCredits, quotedCredits, pricingRevisionId: PRICING_REVISION.id, marginAssumptionBps: PRICING_REVISION.targetContributionMarginBps }; }
