"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { FiArrowRight, FiLock, FiMail } from "react-icons/fi";
import { createClient } from "@/lib/supabase/browser";
import { postSignInDestination } from "@/lib/access/account-state";
export default function SignInPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const [oauthPending, setOauthPending] = useState(false); const router = useRouter();
  useEffect(() => { router.prefetch("/app"); router.prefetch("/pricing"); }, [router]);
  async function submit(event) { event.preventDefault(); if (submitting) return; setSubmitting(true); setError(""); try { const auth = await createClient().auth.signInWithPassword({ email: email.trim(), password }); if (auth.error) throw auth.error; const sync = await fetch("/api/auth/sync", { method: "POST" }); if (!sync.ok) throw new Error("sync"); const account = await fetch("/api/account"); router.replace(postSignInDestination(account)); } catch { setError("Unable to sign in. Check your details or reset your password."); setSubmitting(false); } }
  async function google() { if (oauthPending) return; setOauthPending(true); setError(""); const result = await createClient().auth.signInWithOAuth({ provider: "google", options: { redirectTo: `${location.origin}/auth/callback` } }); if (result.error) { setError("Unable to start Google sign in. Please try again."); setOauthPending(false); } }
  const field = "w-full rounded-xl border border-[#111111]/15 bg-[#FAF8ED] py-3 pl-10 pr-3 text-base outline-none focus:border-[#111111] focus:ring-2 focus:ring-[#111111]/15 disabled:opacity-60";
  return <main className="min-h-screen bg-[#FAF8ED] px-4 py-10 sm:grid sm:place-items-center"><section className="w-full max-w-md rounded-[28px] border border-[#111111]/15 bg-white p-6 shadow-xl sm:p-8"><Link href="/" className="font-serif text-2xl font-bold">Doolphin</Link><p className="mt-8 text-xs font-bold tracking-[.16em] text-[#77746D]">WELCOME BACK</p><h1 className="mt-2 font-serif text-3xl font-bold">Sign in to your Studio</h1><form onSubmit={submit} className="mt-7 space-y-4" aria-busy={submitting}><label className="block text-sm font-semibold" htmlFor="signin-email">Email<span className="relative mt-1.5 block"><FiMail className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#77746D]" /><input id="signin-email" className={field} type="email" autoComplete="email" required placeholder="you@example.com" disabled={submitting} value={email} onChange={(event) => setEmail(event.target.value)} /></span></label><label className="block text-sm font-semibold" htmlFor="signin-password">Password<span className="relative mt-1.5 block"><FiLock className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#77746D]" /><input id="signin-password" className={field} type="password" autoComplete="current-password" required placeholder="Your password" disabled={submitting} value={password} onChange={(event) => setPassword(event.target.value)} /></span></label>{error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<button className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl border border-[#111111] bg-[#111111] px-4 text-sm font-bold text-white shadow-sm transition hover:bg-[#33312C] disabled:cursor-wait disabled:opacity-70" disabled={submitting} aria-busy={submitting}>{submitting ? "Signing in…" : <>Sign in <FiArrowRight /></>}</button></form><button className="mt-3 min-h-11 w-full rounded-xl border border-[#111111]/15 bg-white px-4 text-sm font-semibold hover:bg-[#FAF8ED] disabled:cursor-wait disabled:opacity-60" disabled={oauthPending} aria-busy={oauthPending} onClick={google}>{oauthPending ? "Opening Google…" : "Continue with Google"}</button><p className="mt-6 text-center text-sm text-[#55534E]"><Link className="font-semibold underline" href="/forgot-password">Forgot password?</Link><span className="mx-2">·</span><Link className="font-semibold underline" href="/sign-up">Create account</Link></p></section></main>;
}
