"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { createClient } from "@/lib/supabase/browser";
import { postSignInDestination } from "@/lib/access/account-state";

export default function SignInPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const [oauthPending, setOauthPending] = useState(false); const router = useRouter();
  async function submit(event) { event.preventDefault(); if (submitting) return; setSubmitting(true); setError(""); try { const { error: signInError } = await createClient().auth.signInWithPassword({ email, password }); if (signInError) { setError("Unable to sign in. Check your details or reset your password."); return; } const sync = await fetch("/api/auth/sync", { method: "POST" }); if (!sync.ok) { setError("Signed in, but we could not finish account setup. Please try again."); return; } const account = await fetch("/api/account"); router.replace(postSignInDestination(account)); } catch { setError("Unable to sign in. Check your details or reset your password."); } finally { setSubmitting(false); } }
  async function signInWithGoogle() { if (oauthPending) return; setOauthPending(true); setError(""); const { error: oauthError } = await createClient().auth.signInWithOAuth({ provider: "google", options: { redirectTo: `${location.origin}/auth/callback` } }); if (oauthError) { setError("Unable to start Google sign in. Please try again."); setOauthPending(false); } }
  return <main className="mx-auto max-w-md p-8"><h1 className="font-serif text-4xl font-bold">Sign in</h1><form onSubmit={submit} className="mt-6 space-y-4" aria-busy={submitting}><label className="sr-only" htmlFor="signin-email">Email</label><input id="signin-email" className="w-full border p-3" type="email" required placeholder="Email" disabled={submitting} value={email} onChange={event => setEmail(event.target.value)} /><label className="sr-only" htmlFor="signin-password">Password</label><input id="signin-password" className="w-full border p-3" type="password" required placeholder="Password" disabled={submitting} value={password} onChange={event => setPassword(event.target.value)} />{error && <p className="text-red-700" role="alert">{error}</p>}<button className="w-full rounded bg-black p-3 font-medium text-white disabled:cursor-not-allowed disabled:opacity-60" disabled={submitting} aria-busy={submitting}>{submitting ? "Signing in…" : "Sign in"}</button></form><button className="mt-4 underline disabled:cursor-not-allowed disabled:opacity-60" disabled={oauthPending} aria-busy={oauthPending} onClick={signInWithGoogle}>{oauthPending ? "Connecting to Google…" : "Continue with Google"}</button><p className="mt-6 text-sm"><Link className="underline" href="/forgot-password">Forgot password?</Link> · <Link className="underline" href="/sign-up">Create account</Link></p></main>;
}
