import gptImage2T2I from "./image-definitions/gpt-image-2-text-to-image.js";
import gptImage2I2I from "./image-definitions/gpt-image-2-image-to-image.js";
import seedream5Pro from "./image-definitions/seedream-5-pro.js";
import seedreamV45 from "./image-definitions/seedream-v45.js";
import seedreamV4 from "./image-definitions/seedream-v4.js";
import nanoBanana2Lite from "./image-definitions/nano-banana-2-lite.js";
import nanoBanana2 from "./image-definitions/nano-banana-2.js";
import nanoBananaPro from "./image-definitions/nano-banana-pro.js";
import nanoBanana from "./image-definitions/nano-banana.js";
import grokQuality from "./image-definitions/grok-imagine-quality.js";
import grokImage2 from "./image-definitions/grok-imagine-image-2.js";
import grokI2I from "./image-definitions/grok-imagine-image-to-image.js";
import grokT2I from "./image-definitions/grok-imagine-text-to-image.js";
import { canGenerate, deploymentState } from "./types.js";

/**
 * IMAGE MODEL ENABLEMENT
 * ======================
 * The image studio offers a broad catalogue so users have real choice. Every
 * definition stays in the registry regardless of enablement so its id still
 * RESOLVES -- a request naming a disabled model must fail with "not enabled
 * here" rather than "unknown model". Enablement, not existence, gates spend.
 *
 * Kept as an explicit named allow-list rather than a per-file deployment flag so
 * that "which image models can spend money" is answerable by reading one line.
 */
export const ENABLED_IMAGE_MODEL_IDS = Object.freeze(
  new Set([
    "muapi.gpt-image-2-t2i",
    "muapi.gpt-image-2-i2i",
    "muapi.seedream-v45-t2i",
    "muapi.seedream-v4-t2i",
    "muapi.nano-banana-2-lite-t2i",
    "muapi.nano-banana-2-t2i",
    "muapi.nano-banana-pro-t2i",
    "muapi.nano-banana-t2i",
    "muapi.grok-imagine-quality-t2i",
    "muapi.grok-imagine-i2i",
    "muapi.grok-imagine-t2i",
  ]),
);

/**
 * AVATAR GENERATION IS PINNED TO ONE MODEL
 * ========================================
 * Avatars must be generated with OpenAI GPT Image 2 text-to-image and nothing
 * else. Avatar likeness has to stay consistent across a user's whole library --
 * a face generated by one model and re-generated by another will not match, and
 * the inconsistency is permanent and user-visible.
 *
 * Pinned as a constant rather than a default so it cannot drift: a default would
 * silently follow a change to catalogue ordering or to the enabled set, which is
 * how "the avatar model quietly changed" happens.
 *
 * The avatar UI deliberately does NOT expose this choice. Which model renders a
 * face is an implementation detail, and presenting it as an option would invite
 * users to produce exactly the inconsistency above.
 */
export const AVATAR_GENERATION_MODEL_ID = "muapi.gpt-image-2-t2i";

const RAW_IMAGE_MODELS = [
  gptImage2T2I,
  gptImage2I2I,
  seedream5Pro,
  seedreamV45,
  seedreamV4,
  nanoBanana2Lite,
  nanoBanana2,
  nanoBananaPro,
  nanoBanana,
  grokQuality,
  grokImage2,
  grokI2I,
  grokT2I,
];

// Fail loudly if a definition is missing rather than shipping an `undefined`
// entry. A hole here previously reached the array as a dangling identifier,
// which throws at module load and takes the whole image path down.
for (const [index, model] of RAW_IMAGE_MODELS.entries()) {
  if (!model || typeof model.id !== "string") {
    throw new Error(`Image definition at index ${index} is missing or has no id`);
  }
}

const registeredIds = new Set(RAW_IMAGE_MODELS.map((model) => model.id));
for (const id of ENABLED_IMAGE_MODEL_IDS) {
  if (!registeredIds.has(id)) {
    throw new Error(
      `ENABLED_IMAGE_MODEL_IDS names '${id}', which is not a registered image definition. ` +
        `An enabled-but-unregistered id would silently disable image generation.`,
    );
  }
}

export const IMAGE_MODELS = Object.freeze(
  RAW_IMAGE_MODELS.map((model) =>
    Object.freeze({
      ...model,
      deployments: Object.freeze({
        ...model.deployments,
        staging: ENABLED_IMAGE_MODEL_IDS.has(model.id)
          ? "STAGING_ENABLED"
          : "DISABLED_NOT_IN_PRICING_DOCUMENT",
      }),
    }),
  ),
);

export function getImageModel(id) {
  return IMAGE_MODELS.find((model) => model.id === id) || null;
}

/**
 * The one model permitted to render avatars.
 *
 * Throws rather than falling back if it is unavailable. A fallback would produce
 * an avatar whose likeness does not match the user's existing ones, which is
 * worse than refusing: the bad output is permanent, and the user cannot tell why
 * their face changed.
 */
export function getAvatarGenerationModel(env = process.env) {
  const model = getImageModel(AVATAR_GENERATION_MODEL_ID);
  if (!model) {
    throw new Error(
      `Avatar generation model '${AVATAR_GENERATION_MODEL_ID}' is not registered. Avatars must not fall back to another model.`,
    );
  }
  if (!canGenerate(model, env)) {
    throw new Error(
      `Avatar generation model '${AVATAR_GENERATION_MODEL_ID}' is not enabled in this environment. Refusing to render an avatar with a different model.`,
    );
  }
  return model;
}

/**
 * Guard for any avatar-generation entry point.
 *
 * Exists so the pin is enforced at the point of use rather than trusted. Any
 * future avatar route that accepts a model id must call this, so a client cannot
 * request a different one.
 */
export function assertModelAllowedForAvatarGeneration(modelId) {
  if (modelId && modelId !== AVATAR_GENERATION_MODEL_ID) {
    const error = new Error(
      `Avatars are generated only with '${AVATAR_GENERATION_MODEL_ID}'; '${modelId}' was requested. Model choice is not user-selectable for avatars, so that likeness stays consistent across a user's library.`,
    );
    error.code = "AVATAR_MODEL_NOT_SELECTABLE";
    error.statusCode = 422;
    throw error;
  }
  return AVATAR_GENERATION_MODEL_ID;
}

export function listImageModels(env = process.env) {
  return IMAGE_MODELS.map((model) => ({
    id: model.id,
    displayName: model.displayName,
    mediaType: model.mediaType,
    provider: model.provider,
    status: deploymentState(model, env),
    available: canGenerate(model, env),
    productCapabilities: model.productCapabilities,
    settlementMode: model.settlementMode,
  }));
}
