export class ModelPlatformError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = "ModelPlatformError";
    this.code = code;
    this.details = details;
  }
}

export const ERROR_CODES = Object.freeze({
  MODEL_NOT_FOUND: "MODEL_NOT_FOUND",
  MODEL_DISABLED: "MODEL_DISABLED",
  INVALID_MODEL_INPUT: "INVALID_MODEL_INPUT",
  PROVIDER_SPEC_UNAVAILABLE: "PROVIDER_SPEC_UNAVAILABLE",
  PRICING_UNAVAILABLE: "PRICING_UNAVAILABLE",
  INVALID_PREPARED_PLAN: "INVALID_PREPARED_PLAN",
  PROVIDER_AUTH_UNAVAILABLE: "PROVIDER_AUTH_UNAVAILABLE",
  PROVIDER_REQUEST_FAILED: "PROVIDER_REQUEST_FAILED",
  PROVIDER_RESPONSE_INVALID: "PROVIDER_RESPONSE_INVALID",
  UNTRUSTED_ENDPOINT_REJECTED: "UNTRUSTED_ENDPOINT_REJECTED",
});
