"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { FiImage, FiLoader } from "react-icons/fi";
export default function MyImagesGallery() {
  const [state, setState] = useState({ loading: true, items: [], error: "" });
  const load = async () => { setState((current) => ({ ...current, loading: true, error: "" })); try { const response = await fetch("/api/my-images"); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not load your images."); setState({ loading: false, items: data.items || [], error: "" }); } catch (error) { setState((current) => ({ ...current, loading: false, error: error.message || "Could not load your images." })); } };
  useEffect(() => { void load(); }, []);
  return <div className="h-full overflow-y-auto rounded-[26px] border border-[#111111]/15 bg-[#FAF8ED] p-5 sm:p-8"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-[#111111]/10 pb-5"><div><p className="text-xs font-bold tracking-[0.16em] text-[#77746D]">MY IMAGES</p><h1 className="mt-1 font-serif text-3xl font-bold">Generated images</h1><p className="mt-1 text-sm text-[#66635C]">Images you create in Image Studio are saved here.</p></div><Link href="/app/images" className="rounded-xl border border-[#111111] bg-[#E6D9FF] px-4 py-2.5 text-sm font-semibold hover:bg-[#DBCBFF]">Create an image</Link></header>{state.loading ? <div className="grid min-h-64 place-items-center text-[#66635C]"><FiLoader className="animate-spin" size={24} /></div> : state.error ? <div className="grid min-h-64 place-items-center text-center"><div><p role="alert" className="text-sm text-[#9A2C2C]">{state.error}</p><button type="button" onClick={() => void load()} className="mt-3 underline">Try again</button></div></div> : state.items.length ? <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">{state.items.map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border border-[#111111]/15 bg-white"><img src={item.url} alt={item.prompt || "Generated image"} loading="lazy" className="aspect-square w-full object-cover" /><div className="p-3"><p className="line-clamp-2 text-sm text-[#33312C]">{item.prompt || "Generated image"}</p><p className="mt-1 text-xs text-[#77746D]">{item.modelId}</p></div></article>)}</div> : <div className="grid min-h-72 place-items-center text-center"><div><FiImage className="mx-auto text-[#77746D]" size={32} /><h2 className="mt-3 font-serif text-xl font-bold">No generated images yet</h2><p className="mt-1 text-sm text-[#66635C]">Create your first image from a prompt or reference.</p><Link href="/app/images" className="mt-4 inline-block rounded-xl border border-[#111111] bg-[#E6D9FF] px-4 py-2.5 text-sm font-semibold">Open Image Studio</Link></div></div>}</div>;
}
