"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { FiArrowRight, FiLock, FiMail } from "react-icons/fi";
const TERMS = "legal_terms_v1"; const PRIVACY = "legal_privacy_v1"; const ERROR = "We couldn’t create a new account with those details. Try signing in or resetting your password.";
export default function SignUpPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const router = useRouter();
  useEffect(() => { router.prefetch("/verify-email"); }, [router]);
  async function submit(event) { event.preventDefault(); if (submitting) return; if (password !== confirm) return setError("Passwords do not match."); setSubmitting(true); setError(""); try { const response = await fetch("/api/auth/sign-up", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: email.trim(), password, acceptedVersions: [TERMS, PRIVACY] }) }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || ERROR); sessionStorage.setItem("doolphin_pending_consent", JSON.stringify([TERMS, PRIVACY])); router.replace(`/verify-email?email=${encodeURIComponent(email.trim())}`); } catch (reason) { setError(reason.message || ERROR); setSubmitting(false); } }
  const field = "w-full rounded-xl border border-[#111111]/15 bg-[#FAF8ED] py-3 pl-10 pr-3 text-base outline-none focus:border-[#111111] focus:ring-2 focus:ring-[#111111]/15 disabled:opacity-60";
  return <main className="min-h-screen bg-[#FAF8ED] px-4 py-10 sm:grid sm:place-items-center"><section className="w-full max-w-md rounded-[28px] border border-[#111111]/15 bg-white p-6 shadow-xl sm:p-8"><Link href="/" className="font-serif text-2xl font-bold">Doolphin</Link><p className="mt-8 text-xs font-bold tracking-[.16em] text-[#77746D]">START CREATING</p><h1 className="mt-2 font-serif text-3xl font-bold">Create your account</h1><form onSubmit={submit} className="mt-7 space-y-4" aria-busy={submitting}><label className="block text-sm font-semibold" htmlFor="signup-email">Email<span className="relative mt-1.5 block"><FiMail className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#77746D]" /><input id="signup-email" className={field} type="email" autoComplete="email" required placeholder="you@example.com" disabled={submitting} value={email} onChange={(event) => setEmail(event.target.value)} /></span></label><label className="block text-sm font-semibold" htmlFor="signup-password">Password<span className="relative mt-1.5 block"><FiLock className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#77746D]" /><input id="signup-password" className={field} type="password" autoComplete="new-password" minLength="8" required placeholder="At least 8 characters" disabled={submitting} value={password} onChange={(event) => setPassword(event.target.value)} /></span></label><label className="block text-sm font-semibold" htmlFor="signup-confirm">Confirm password<span className="relative mt-1.5 block"><FiLock className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#77746D]" /><input id="signup-confirm" className={field} type="password" autoComplete="new-password" required placeholder="Repeat password" disabled={submitting} value={confirm} onChange={(event) => setConfirm(event.target.value)} /></span></label><p className="text-sm text-[#55534E]">By creating an account, you agree to the <Link className="font-semibold underline" href="/terms">Terms</Link> and <Link className="font-semibold underline" href="/privacy">Privacy Policy</Link>.</p>{error && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<button className="auth-primary-btn flex min-h-12 w-full items-center justify-center gap-2 rounded-xl text-white px-4 text-sm font-bold shadow-sm transition disabled:cursor-wait" disabled={submitting} aria-busy={submitting}>{submitting ? <span>Creating account…</span> : <><span className="font-bold">Create account</span> <FiArrowRight /></>}</button></form><p className="mt-6 text-center text-sm text-[#55534E]">Already have an account? <Link className="font-semibold underline" href="/sign-in">Sign in</Link></p></section></main>;
}
