"use client";

import { useEffect, useMemo, useState } from "react";
import { FiCheck, FiChevronDown, FiSearch } from "react-icons/fi";

export default function StudioModelPicker({ models = [], value, onChange, label = "AI model" }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState("");
  useEffect(() => { const close = (event) => { if (event.key === "Escape") setOpen(false); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);
  const selected = models.find((model) => model.id === value) || models[0];
  const visible = useMemo(() => models.filter((model) => `${model.name} ${model.description || ""}`.toLowerCase().includes(query.toLowerCase())), [models, query]);
  return <div className="relative"><button type="button" onClick={() => setOpen((state) => !state)} aria-haspopup="listbox" aria-expanded={open} className="flex w-full items-center justify-between rounded-xl border border-[#111111]/15 bg-[#F2EFE5] px-3.5 py-3 text-left text-sm font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#111111]"><span className="truncate">{selected?.name || label}</span><FiChevronDown /></button>{open && <div className="absolute left-0 top-[calc(100%+0.5rem)] z-50 w-full overflow-hidden rounded-2xl border border-[#111111]/15 bg-white p-2 shadow-xl"><label className="relative block"><FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-[#77746D]" /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search models" className="w-full rounded-xl border border-[#111111]/15 bg-[#FAF8ED] py-2 pl-9 pr-3 text-sm outline-none focus:border-[#111111]" /></label><div role="listbox" aria-label={label} className="mt-1 max-h-56 overflow-y-auto">{visible.map((model) => <button key={model.id} type="button" role="option" aria-selected={model.id === selected?.id} onClick={() => { onChange(model); setOpen(false); setQuery(""); }} className="flex w-full items-start justify-between gap-3 rounded-xl px-3 py-2.5 text-left hover:bg-[#EFECE1] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#111111]"><span className="min-w-0"><span className="block truncate text-sm font-semibold">{model.name}</span>{model.description && <span className="block line-clamp-1 text-xs text-[#77746D]">{model.description}</span>}<span className="mt-1 block text-[11px] text-[#77746D]">{model.resolutions?.join(" · ") || "Provider settings"} {model.aspectRatios?.length ? `· ${model.aspectRatios.join(", ")}` : ""}</span></span>{model.id === selected?.id && <FiCheck className="mt-1 shrink-0" />}</button>)}</div></div>}</div>;
}
